export const globalCity = [
  {
    name: 'A',
    city:[
      {"cityId": "843", "cityName": "阿伯丁"},
      {"cityId": "194","cityName": "阿布扎比"},
      {"cityId": "4","cityName": "阿德莱德"},
      {"cityId": "1143","cityName": "阿尔伯里"},
      {"cityId": "4711","cityName": "阿尔伯斯塔特"},
      {"cityId": "1080","cityName": "阿尔勒"},
      {"cityId": "4085","cityName": "阿寒国立公园"},
      {"cityId": "3428","cityName": "阿吉曼"},
      {"cityId": "1286","cityName": "阿拉木图"},
      {"cityId": "8523","cityName": "阿里山"},
      {"cityId": "153","cityName": "阿姆斯特丹"},
      {"cityId": "1575","cityName": "阿斯塔纳"},
      {"cityId": "145","cityName": "阿维尼翁"},
      {"cityId": "1046","cityName": "阿治曼"},
      {"cityId": "5455","cityName": "埃尔丁"},
      {"cityId": "5432","cityName": "埃尔兰根"},
      {"cityId": "5542","cityName": "埃尔姆边的孔宁斯路特"},
      {"cityId": "5527","cityName": "埃尔特维勒"},
      {"cityId": "1389","cityName": "埃格尔"},
      {"cityId": "5494","cityName": "埃青"},
      {"cityId": "2049","cityName": "埃森"},
      {"cityId": "149","cityName": "埃斯波",},
      {"cityId": "3741","cityName": "埃文河畔斯特拉福德"},
      {"cityId": "1108","cityName": "埃武拉"},
      {"cityId": "3815","cityName": "艾恩"},
      {"cityId": "1687","cityName": "艾丽斯斯普林斯"},
      {"cityId": "192","cityName": "爱丁堡"},
      {"cityId": "1917","cityName": "爱尔福特"},
      {"cityId": "3568","cityName": "安贝格"},
      {"cityId": "5495","cityName": "安达赫治"},
      {"cityId": "2053","cityName": "安道尔"},
      {"cityId": "3440","cityName": "安东"},
      {"cityId": "1501","cityName": "安科纳"},
      {"cityId": "1605","cityName": "安塔利亚"},
      {"cityId": "123","cityName": "安特卫普"},
      {"cityId": "1075","cityName": "昂热"},
      {"cityId": "1113","cityName": "奥比杜什"},
      {"cityId": "4699","cityName": "奥伯豪森"},
      {"cityId": "4706","cityName": "奥博茨豪森"},
      {"cityId": "3567","cityName": "奥德河畔的法兰克福"},
      {"cityId": "637","cityName": "奥尔巴尼"},
      {"cityId": "1383","cityName": "奥尔堡"},
      {"cityId": "894","cityName": "奥尔伯尼(奥尔巴尼)"},
      {"cityId": "3560","cityName": "奥芬巴赫",},
      {"cityId": "3566","cityName": "奥芬堡"},
      {"cityId": "3513","cityName": "奥格斯堡"},
      {"cityId": "126","cityName": "奥胡斯"},
      {"cityId": "14","cityName": "奥克兰"},
      {"cityId": "62","cityName": "奥兰多"},
      {"cityId": "174","cityName": "奥林匹亚"},
      {"cityId": "1262","cityName": "奥卢"},
      {"cityId": "24","cityName": "奥马鲁"},
      {"cityId": "157","cityName": "奥斯陆"},
      {"cityId": "3552","cityName": "奥斯纳布吕克"},
      {"cityId": "4707","cityName": "奥滕贝格"},
      {"cityId": "1270","cityName": "澳门"},
    ],
  },{
    name: 'B',
    city:[
      {"cityId": "3915","cityName": "八打灵再也"},
      {"cityId": "1253","cityName": "巴德依舍"},
      {"cityId": "1088","cityName": "巴登-巴登"},
      {"cityId": "5502","cityName": "巴登豪舍"},
      {"cityId": "644","cityName": "巴尔的摩"},
      {"cityId": "248","cityName": "巴厘岛"},
      {"cityId": "138","cityName": "巴黎"},
      {"cityId": "952","cityName": "巴利亚多利德"},
      {"cityId": "293","cityName": "巴伦西亚"},
      {"cityId": "937","cityName": "巴塞尔"},
      {"cityId": "168","cityName": "巴塞罗那"},
      {"cityId": "4575","cityName": "巴瑟尔顿"},
      {"cityId": "3447","cityName": "巴生"},
      {"cityId": "1319","cityName": "巴斯"},
      {"cityId": "3564","cityName": "巴特洪堡"},
      {"cityId": "5520","cityName": "巴特克罗伊茨纳赫"},
      {"cityId": "4709","cityName": "巴特诺因阿尔-阿尔韦勒"},
      {"cityId": "233","cityName": "芭堤雅"},
      {"cityId": "3469","cityName": "芭东"},
      {"cityId": "3466","cityName": "白川村"},
      {"cityId": "4759","cityName": "白川乡"},
      {"cityId": "131","cityName": "柏林"},
      {"cityId": "4659","cityName": "拜恩斯代尔"},
      {"cityId": "1129","cityName": "拜伦贝"},
      {"cityId": "3543","cityName": "拜罗伊特"},
      {"cityId": "3415","cityName": "拜县"},
      {"cityId": "1095","cityName": "班贝格"},
      {"cityId": "974","cityName": "卑尔根"},
      {"cityId": "4369","cityName": "北碧"},
      {"cityId": "3453","cityName": "北海道--登别"},
      {"cityId": "552","cityName": "北海道--函馆"},
      {"cityId": "3451","cityName": "北海道--小樽"},
      {"cityId": "3347","cityName": "北海道--旭川"},
      {"cityId": "224","cityName": "北海道--札幌"},
      {"cityId": "5138","cityName": "北河"},
      {"cityId": "3462","cityName": "北九州市"},
      {"cityId": "5465","cityName": "贝恩堡"},
      {"cityId": "5447","cityName": "贝尔恩卡斯特尔-库埃斯"},
      {"cityId": "840","cityName": "贝尔法斯特"},
      {"cityId": "1409","cityName": "贝尔格莱德"},
      {"cityId": "5650","cityName": "贝加尔湖"},
      {"cityId": "3503","cityName": "贝希特斯加登"},
      {"cityId": "2065","cityName": "比勒费尔德"},
      {"cityId": "1381","cityName": "比隆"},
      {"cityId": "1099","cityName": "比萨"},
      {"cityId": "1321","cityName": "比斯特"},
      {"cityId": "1054","cityName": "彼得宫城"},
      {"cityId": "172","cityName": "毕尔巴鄂"},
      {"cityId": "557","cityName": "槟城"},
      {"cityId": "5135","cityName": "槟椥"},
      {"cityId": "1083","cityName": "波茨坦"},
      {"cityId": "3930","cityName": "波德申"},
      {"cityId": "2047","cityName": "波恩"},
      {"cityId": "305","cityName": "波尔多"},
      {"cityId": "286","cityName": "波尔图"},
      {"cityId": "3527","cityName": "波鸿"},
      {"cityId": "50","cityName": "波士顿"},
      {"cityId": "1235","cityName": "波兹南"},
      {"cityId": "5550","cityName": "伯尔根"},
      {"cityId": "164","cityName": "伯尔尼"},
      {"cityId": "189","cityName": "伯明翰"},
      {"cityId": "3563","cityName": "博登湖畔克雷斯波洛"},
      {"cityId": "947","cityName": "博洛尼亚"},
      {"cityId": "5426","cityName": "博帕尔德"},
      {"cityId": "3820","cityName": "薄荷岛"},
      {"cityId": "3506","cityName": "不来梅"},
      {"cityId": "3532","cityName": "不伦瑞克"},
      {"cityId": "3449","cityName": "布城"},
      {"cityId": "177","cityName": "布达佩斯"},
      {"cityId": "155","cityName": "布尔诺"},
      {"cityId": "653","cityName": "布法罗"},
      {"cityId": "154","cityName": "布拉格"},
      {"cityId": "1387","cityName": "布拉提斯拉法"},
      {"cityId": "3737","cityName": "布莱顿"},
      {"cityId": "5471","cityName": "布赖斯高的施陶芬"},
      {"cityId": "4673","cityName": "布雷斯湾"},
      {"cityId": "5","cityName": "布里斯班"},
      {"cityId": "842","cityName": "布里斯托尔"},
      {"cityId": "70","cityName": "布鲁克林"},
      {"cityId": "1240","cityName": "布鲁日"},
      {"cityId": "122","cityName": "布鲁塞尔"},
      {"cityId": "3550","cityName": "布吕尔"},
      {"cityId": "3409","cityName": "布伦瑞克"},
      {"cityId": "109","cityName": "布宜诺斯艾利斯"},
    ],
  },
  {
    name: 'C',
    city:[
      {"cityId": "1205","cityName": "采尔马特",},
      {"cityId": "8543","cityName": "层云峡",},
      {"cityId": "265","cityName": "长岛",},
      {"cityId": "225","cityName": "长崎",},
      {"cityId": "4140","cityName": "长野市",},
      {"cityId": "4082","cityName": "长野县",},
      {"cityId": "4115","cityName": "成田市",},
      {"cityId": "222","cityName": "冲绳--那霸",},
      {"cityId": "4088","cityName": "冲绳市",},
      {"cityId": "4090","cityName": "钏路市",},
      {"cityId": "3433","cityName": "春川",},
      {"cityId": "229","cityName": "茨城",},
      {"cityId": "1007","cityName": "茨城县",},
      {"cityId": "5409","cityName": "茨维考",},
    ],
  },
  {
    name: 'D',
    city:[
      {"cityId": "52","cityName": "达拉斯",},
      {"cityId": "5407","cityName": "达姆施塔特",},
      {"cityId": "1509","cityName": "达尼丁",},
      {"cityId": "218","cityName": "大阪",},
      {"cityId": "1027","cityName": "大城",},
      {"cityId": "1297","cityName": "大分",},
      {"cityId": "1433","cityName": "大叻",},
      {"cityId": "500","cityName": "大邱",},
      {"cityId": "3436","cityName": "大田",},
      {"cityId": "641","cityName": "大西洋城",},
      {"cityId": "8554","cityName": "大洋路",},
      {"cityId": "8610","cityName": "带广市",},
      {"cityId": "4120","cityName": "帯広",},
      {"cityId": "3779","cityName": "袋鼠岛",},
      {"cityId": "63","cityName": "丹佛",},
      {"cityId": "9","cityName": "道格拉斯港",},
      {"cityId": "3692","cityName": "德尔斐",},
      {"cityId": "1082","cityName": "德累斯顿",},
      {"cityId": "3538","cityName": "德绍",},
      {"cityId": "193","cityName": "迪拜",},
      {"cityId": "72","cityName": "底特律",},
      {"cityId": "1078","cityName": "第戎",},
      {"cityId": "28","cityName": "蒂阿瑙",},
      {"cityId": "3546","cityName": "蒂蒂湖-新城",},
      {"cityId": "3419","cityName": "蒂卡波湖",},
      {"cityId": "30","cityName": "蒂马鲁",},
      {"cityId": "3535","cityName": "丁克尔斯比尔",},
      {"cityId": "8544","cityName": "定山溪",},
      {"cityId": "217","cityName": "东京",},
      {"cityId": "3454","cityName": "洞爷湖",},
      {"cityId": "116","cityName": "都柏林",},
      {"cityId": "185","cityName": "都灵",},
      {"cityId": "130","cityName": "杜塞尔多夫",},
      {"cityId": "3519","cityName": "杜伊斯堡",},
      {"cityId": "1281","cityName": "多哈",},
      {"cityId": "37","cityName": "多伦多",},
      {"cityId": "5480","cityName": "多瑙沃特",},
      {"cityId": "1092","cityName": "多特蒙德",},
    ],
  },
  {
    name: 'E',
    city:[
      {"cityId": "156","cityName": "俄斯特拉发",},
      {"cityId": "4168","cityName": "二世古",},
    ],
  },
  {
    name: 'F',
    city:[
      {"cityId": "1112","cityName": "法蒂玛",},
      {"cityId": "128","cityName": "法兰克福",},
      {"cityId": "1110","cityName": "法鲁",},
      {"cityId": "5124","cityName": "藩切",},
      {"cityId": "1074","cityName": "凡尔赛",},
      {"cityId": "5501","cityName": "菲尔特",},
      {"cityId": "1254","cityName": "菲拉赫",},
      {"cityId": "3786","cityName": "菲利普岛",},
      {"cityId": "1441","cityName": "腓特烈港",},
      {"cityId": "66","cityName": "费城",},
      {"cityId": "1683","cityName": "丰沙尔",},
      {"cityId": "4121","cityName": "丰田市",},
      {"cityId": "1073","cityName": "枫丹白露",},
      {"cityId": "183","cityName": "佛罗伦萨",},
      {"cityId": "3508","cityName": "弗赖堡",},
      {"cityId": "5433","cityName": "弗赖辛",},
      {"cityId": "5410","cityName": "弗伦斯堡",},
      {"cityId": "1264","cityName": "弗罗茨瓦夫",},
      {"cityId": "3553","cityName": "弗罗伊登施塔特",},
      {"cityId": "1357","cityName": "弗洛姆",},
      {"cityId": "3917","cityName": "芙蓉市",},
      {"cityId": "228","cityName": "福冈",},
      {"cityId": "3421","cityName": "福克斯冰川",},
      {"cityId": "3413","cityName": "福森",},
      {"cityId": "5556","cityName": "福伊希特旺根",},
      {"cityId": "206","cityName": "釜山",},
      {"cityId": "1047","cityName": "富查伊拉",},
      {"cityId": "5405","cityName": "富尔达",},
      {"cityId": "5130","cityName": "富国岛",},
      {"cityId": "3430","cityName": "富吉拉",},
      {"cityId": "4077","cityName": "富良野",},
      {"cityId": "2131","cityName": "富纳富蒂",},
      {"cityId": "551","cityName": "富山市",},
      {"cityId": "4084","cityName": "富士河口湖",},
      {"cityId": "3450","cityName": "富士山",},
      {"cityId": "4112","cityName": "富士五湖地区",},
    ],
  },
  {
    name: 'G',
    city:[
      {"cityId": "3562","cityName": "盖尔森基兴",},
      {"cityId": "3620","cityName": "盖朗厄尔",},
      {"cityId": "6114","cityName": "盖朗厄尔峡湾",},
      {"cityId": "4086","cityName": "冈山市",},
      {"cityId": "1012","cityName": "高山",},
      {"cityId": "4110","cityName": "高山市",},
      {"cityId": "277","cityName": "高雄",},
      {"cityId": "5413","cityName": "戈斯拉尔",},
      {"cityId": "125","cityName": "哥本哈根",},
      {"cityId": "5439","cityName": "哥达",},
      {"cityId": "160","cityName": "哥德堡",},
      {"cityId": "3525","cityName": "哥廷根",},
      {"cityId": "1385","cityName": "格但斯克",},
      {"cityId": "118","cityName": "格拉茨",},
      {"cityId": "291","cityName": "格拉纳达",},
      {"cityId": "190","cityName": "格拉斯哥",},
      {"cityId": "853","cityName": "格勒诺布尔",},
      {"cityId": "25","cityName": "格雷茅斯",},
      {"cityId": "993","cityName": "根特",},
      {"cityId": "4094","cityName": "宫崎市",},
      {"cityId": "5549","cityName": "贡岑豪森",},
      {"cityId": "3923","cityName": "古达",},
      {"cityId": "1033","cityName": "古来",},
      {"cityId": "3911","cityName": "瓜拉雪兰莪",},
      {"cityId": "3446","cityName": "关丹",},
      {"cityId": "8621","cityName": "关岛",},
      {"cityId": "3434","cityName": "光州",},
      {"cityId": "546","cityName": "广岛",},
      {"cityId": "3530","cityName": "国王湖畔的舍瑙",},
    ],
  },
  {
    name: 'H',
    city:[
      {"cityId": "4708","cityName": "哈尔伯斯塔德",},
      {"cityId": "1246","cityName": "哈尔施塔特",},
      {"cityId": "5557","cityName": "哈格瑙",},
      {"cityId": "3554","cityName": "哈雷",},
      {"cityId": "3549","cityName": "哈瑙",},
      {"cityId": "1421","cityName": "哈瓦那",},
      {"cityId": "1045","cityName": "哈伊马角",},
      {"cityId": "1087","cityName": "海德堡",},
      {"cityId": "5123","cityName": "海防市",},
      {"cityId": "152","cityName": "海牙市",},
      {"cityId": "132","cityName": "汉堡",},
      {"cityId": "15","cityName": "汉密尔顿",},
      {"cityId": "1094","cityName": "汉诺威",},
      {"cityId": "720","cityName": "汉诺威（马里兰州）",},
      {"cityId": "1010","cityName": "和歌山",},
      {"cityId": "5137","cityName": "河江",},
      {"cityId": "250","cityName": "河内",},
      {"cityId": "3817","cityName": "赫达",},
      {"cityId": "1691","cityName": "赫尔格达",},
      {"cityId": "3500","cityName": "赫尔辛格",},
      {"cityId": "146","cityName": "赫尔辛基",},
      {"cityId": "1693","cityName": "赫罗纳",},
      {"cityId": "5535","cityName": "黑伯恩",},
      {"cityId": "4701","cityName": "黑彭海姆",},
      {"cityId": "220","cityName": "横滨",},
      {"cityId": "251","cityName": "胡志明市",},
      {"cityId": "1395","cityName": "湖区",},
      {"cityId": "281","cityName": "花莲",},
      {"cityId": "298","cityName": "华沙",},
      {"cityId": "49","cityName": "华盛顿",},
      {"cityId": "1287","cityName": "华欣",},
      {"cityId": "676","cityName": "滑铁卢(纽约州)",},
      {"cityId": "33","cityName": "皇后镇",},
      {"cityId": "6","cityName": "黄金海岸",},
      {"cityId": "5119","cityName": "会安",},
      {"cityId": "21","cityName": "惠灵顿",},
      {"cityId": "893","cityName": "霍巴特",},
    ],
  },
  {
    name: 'J',
    city:[
      {"cityId": "32","cityName": "基督城",},
      {"cityId": "1959","cityName": "基尔",},
      {"cityId": "280","cityName": "基隆",},
      {"cityId": "211","cityName": "吉隆坡",},
      {"cityId": "3461","cityName": "纪伊半岛",},
      {"cityId": "1140","cityName": "季隆",},
      {"cityId": "205","cityName": "济州岛",},
      {"cityId": "213","cityName": "加德满都",},
      {"cityId": "844","cityName": "加的夫"},
      {"cityId": "1085","cityName": "加米施－帕滕基兴"},
      {"cityId": "8525","cityName": "加平"},
      {"cityId": "3949","cityName": "加影"},
      {"cityId": "1035","cityName": "嘉义"},
      {"cityId": "143","cityName": "戛纳"},
      {"cityId": "3345","cityName": "甲府市"},
      {"cityId": "1291","cityName": "甲米"},
      {"cityId": "994","cityName": "剑桥"},
      {"cityId": "3788","cityName": "箭镇"},
      {"cityId": "3862","cityName": "江村"},
      {"cityId": "3438","cityName": "江陵"},
      {"cityId": "4574","cityName": "杰拉尔顿"},
      {"cityId": "209","cityName": "金边",},
      {"cityId": "3867","cityName": "金堤市",},
      {"cityId": "3907","cityName": "金马伦高地",},
      {"cityId": "1359","cityName": "金沙维克",},
      {"cityId": "1014","cityName": "金泽",},
      {"cityId": "5521","cityName": "近弗赖兴的诺伊法尔恩",},
      {"cityId": "501","cityName": "晋州",},
      {"cityId": "227","cityName": "京都",},
      {"cityId": "1006","cityName": "静冈县",},
      {"cityId": "3866","cityName": "九里市",},
      {"cityId": "44","cityName": "旧金山",},
      {"cityId": "8530","cityName": "巨济",},
      {"cityId": "3735","cityName": "巨石阵",},
    ],
  },
  {
    name: 'K',
    city:[
      {"cityId": "136","cityName": "喀山",},
      {"cityId": "4576","cityName": "卡尔巴里",},
      {"cityId": "40","cityName": "卡尔加里",},
      {"cityId": "1077","cityName": "卡尔卡松",},
      {"cityId": "1465","cityName": "卡尔斯鲁厄",},
      {"cityId": "1224","cityName": "卡尔斯塔德",},
      {"cityId": "1230","cityName": "卡罗维发利",},
      {"cityId": "3407","cityName": "卡帕多奇亚",},
      {"cityId": "3654","cityName": "卡帕多西亚",},
      {"cityId": "100","cityName": "卡萨布兰卡",},
      {"cityId": "3529","cityName": "卡塞尔",},
      {"cityId": "171","cityName": "卡塞雷斯",},
      {"cityId": "3625","cityName": "卡斯凯什",},
      {"cityId": "1150","cityName": "卡通巴",},
      {"cityId": "85","cityName": "开罗",},
      {"cityId": "82","cityName": "开普敦",},
      {"cityId": "7","cityName": "凯恩斯",},
      {"cityId": "22","cityName": "凯库拉",},
      {"cityId": "1259","cityName": "凯米",},
      {"cityId": "273","cityName": "堪培拉",},
      {"cityId": "1325","cityName": "坎特伯雷",},
      {"cityId": "1086","cityName": "康斯坦茨",},
      {"cityId": "1069","cityName": "考文垂",},
      {"cityId": "1160","cityName": "科堡",},
      {"cityId": "1093","cityName": "科布伦茨",},
      {"cityId": "3743","cityName": "科茨沃尔德",},
      {"cityId": "1104","cityName": "科尔多瓦",},
      {"cityId": "5427","cityName": "科赫姆",},
      {"cityId": "270","cityName": "科隆",},
      {"cityId": "1282","cityName": "科伦坡",},
      {"cityId": "1236","cityName": "克拉科夫",},
      {"cityId": "852","cityName": "克莱蒙费朗",},
      {"cityId": "5464","cityName": "克劳斯塔尔-采勒费尔德",},
      {"cityId": "1355","cityName": "克里斯蒂安桑",},
      {"cityId": "1367","cityName": "克里斯蒂安松",},
      {"cityId": "3687","cityName": "克里特岛",},
      {"cityId": "662","cityName": "克利夫兰",},
      {"cityId": "1228","cityName": "克鲁姆洛夫",},
      {"cityId": "4700","cityName": "肯普滕",},
      {"cityId": "1037","cityName": "垦丁",},
      {"cityId": "3804","cityName": "库克山镇",},
      {"cityId": "5488","cityName": "库克斯港",},
      {"cityId": "1123","cityName": "库兰达",},
      {"cityId": "1229","cityName": "库特纳霍拉",},
      {"cityId": "5420","cityName": "奎德林堡",},
    ],
  },
  {
    name: 'L',
    city:[
      {"cityId": "170","cityName": "拉科鲁尼亚",},
      {"cityId": "5411","cityName": "拉姆绍",},
      {"cityId": "1260","cityName": "拉普兰",},
      {"cityId": "3429","cityName": "拉斯海马",},
      {"cityId": "45","cityName": "拉斯维加斯",},
      {"cityId": "5509","cityName": "拉廷根",},
      {"cityId": "1329","cityName": "莱比锡",},
      {"cityId": "1193","cityName": "莱顿",},
      {"cityId": "1317","cityName": "莱斯特",},
      {"cityId": "5456","cityName": "莱茵河畔威尔",},
      {"cityId": "1271","cityName": "兰卡威",},
      {"cityId": "1071","cityName": "兰斯",},
      {"cityId": "2","cityName": "蓝山",},
      {"cityId": "689","cityName": "劳德代尔堡",},
      {"cityId": "3545","cityName": "勒沃库森",},
      {"cityId": "1066","cityName": "雷丁",},
      {"cityId": "864","cityName": "雷恩",},
      {"cityId": "3518","cityName": "雷根斯堡",},
      {"cityId": "124","cityName": "雷克雅未克",},
      {"cityId": "8527","cityName": "骊州",},
      {"cityId": "142","cityName": "里昂",},
      {"cityId": "302","cityName": "里尔",},
      {"cityId": "761","cityName": "里士满",},
      {"cityId": "158","cityName": "里斯本",},
      {"cityId": "113","cityName": "里约热内卢",},
      {"cityId": "3439","cityName": "丽水",},
      {"cityId": "1363","cityName": "利勒哈默尔",},
      {"cityId": "3816","cityName": "利瓦绿洲",},
      {"cityId": "838","cityName": "利物浦",},
      {"cityId": "837","cityName": "利兹",},
      {"cityId": "1005","cityName": "栃木县",},
      {"cityId": "4076","cityName": "镰仓",},
      {"cityId": "5129","cityName": "谅山",},
      {"cityId": "1164","cityName": "列治文",},
      {"cityId": "119","cityName": "林茨",},
      {"cityId": "3515","cityName": "林道",},
      {"cityId": "1225","cityName": "林雪平",},
      {"cityId": "3682","cityName": "龙达",},
      {"cityId": "3425","cityName": "龙仁市",},
      {"cityId": "1869","cityName": "卢尔德",},
      {"cityId": "1206","cityName": "卢加诺",},
      {"cityId": "1210","cityName": "卢塞恩",},
      {"cityId": "1415","cityName": "卢森堡",},
      {"cityId": "1243","cityName": "卢森堡省",},
      {"cityId": "547","cityName": "鹿儿岛",},
      {"cityId": "151","cityName": "鹿特丹",},
      {"cityId": "5414","cityName": "路德城维滕贝格",},
      {"cityId": "3558","cityName": "路德维希堡",},
      {"cityId": "3514","cityName": "吕贝克",},
      {"cityId": "3520","cityName": "吕德斯海姆",},
      {"cityId": "3542","cityName": "吕根岛",},
      {"cityId": "5406","cityName": "吕讷堡",},
      {"cityId": "3565","cityName": "吕塞尔斯海姆",},
      {"cityId": "187","cityName": "伦敦",},
      {"cityId": "5541","cityName": "罗德马克",},
      {"cityId": "1258","cityName": "罗凡涅米",},
      {"cityId": "5481","cityName": "罗拉赫",},
      {"cityId": "181","cityName": "罗马",},
      {"cityId": "4703","cityName": "罗斯豪普滕",},
      {"cityId": "3502","cityName": "罗斯基勒",},
      {"cityId": "5534","cityName": "罗斯拉特",},
      {"cityId": "3540","cityName": "罗斯托克",},
      {"cityId": "3504","cityName": "罗滕堡",},
      {"cityId": "5440","cityName": "罗滕伯格",},
      {"cityId": "16","cityName": "罗托鲁瓦",},
      {"cityId": "1341","cityName": "罗瓦涅米",},
      {"cityId": "1234","cityName": "罗兹",},
      {"cityId": "161","cityName": "洛桑",},
      {"cityId": "42","cityName": "洛杉矶",},
    ],
  },
  {
    name: 'M',
    city:[

    ],
  },
  {
    name: 'N',
    city:[
      {"cityId": "1032","cityName": "麻坡",},
      {"cityId": "1109","cityName": "马德拉",},
      {"cityId": "167","cityName": "马德里",},
      {"cityId": "3541","cityName": "马尔堡",},
      {"cityId": "975","cityName": "马尔默",},
      {"cityId": "8675","cityName": "马耳他",},
      {"cityId": "3534","cityName": "马格德堡",},
      {"cityId": "292","cityName": "马拉加",},
      {"cityId": "1655","cityName": "马拉喀什",},
      {"cityId": "558","cityName": "马六甲",},
      {"cityId": "200","cityName": "马尼拉",},
      {"cityId": "140","cityName": "马赛",},
      {"cityId": "4560","cityName": "玛格丽特河",},
      {"cityId": "51","cityName": "迈阿密",},
      {"cityId": "3548","cityName": "迈森",},
      {"cityId": "726","cityName": "麦迪逊",},
      {"cityId": "1089","cityName": "麦琴根",},
      {"cityId": "188","cityName": "曼彻斯特",},
      {"cityId": "230","cityName": "曼谷",},
      {"cityId": "3511","cityName": "曼海姆",},
      {"cityId": "5122","cityName": "芒街",},
      {"cityId": "1081","cityName": "芒通",},
      {"cityId": "982","cityName": "毛里求斯",},
      {"cityId": "1247","cityName": "梅尔克",},
      {"cityId": "3561","cityName": "梅明根",},
      {"cityId": "3510","cityName": "梅青根",},
      {"cityId": "5118","cityName": "美奈",},
      {"cityId": "5127","cityName": "美拖",},
      {"cityId": "3509","cityName": "美因茨",},
      {"cityId": "4079","cityName": "美瑛",},
      {"cityId": "3551","cityName": "门兴格拉德巴赫",},
      {"cityId": "858","cityName": "蒙彼利埃",},
      {"cityId": "261","cityName": "蒙市",},
      {"cityId": "1443","cityName": "蒙斯特",},
      {"cityId": "1208","cityName": "蒙特勒",},
      {"cityId": "38","cityName": "蒙特利尔",},
      {"cityId": "3790","cityName": "米尔福德峡湾",},
      {"cityId": "180","cityName": "米兰",},
      {"cityId": "1154","cityName": "密西沙加",},
      {"cityId": "3653","cityName": "棉花堡",},
      {"cityId": "1039","cityName": "苗栗",},
      {"cityId": "223","cityName": "名古屋",},
      {"cityId": "1293","cityName": "明斯克",},
      {"cityId": "3526","cityName": "明斯特",},
      {"cityId": "300","cityName": "摩纳哥",},
      {"cityId": "133","cityName": "莫斯科",},
      {"cityId": "3","cityName": "墨尔本",},
      {"cityId": "73","cityName": "墨西哥城",},
      {"cityId": "3443","cityName": "木浦",},
      {"cityId": "129","cityName": "慕尼黑",},
      {"cityId": "3559","cityName": "慕尼黑旁的嘉尔兴",},
      {"cityId": "98","cityName": "内罗毕",},
      {"cityId": "184","cityName": "那波里",},
      {"cityId": "944","cityName": "那不勒斯",},
      {"cityId": "1116","cityName": "纳尔逊（尼尔森）",},
      {"cityId": "221","cityName": "奈良",},
      {"cityId": "841","cityName": "南安普敦",},
      {"cityId": "860","cityName": "南特",},
      {"cityId": "1044","cityName": "南投",},
      {"cityId": "997","cityName": "楠迪",},
      {"cityId": "3555","cityName": "讷德林根",},
      {"cityId": "5528","cityName": "尼布尔",},
      {"cityId": "1079","cityName": "尼姆",},
      {"cityId": "139","cityName": "尼斯",},
      {"cityId": "3736","cityName": "尼斯湖",},
      {"cityId": "5133","cityName": "宁平",},
      {"cityId": "1064","cityName": "牛津",},
      {"cityId": "1172","cityName": "纽黑文",},
      {"cityId": "1697","cityName": "纽基",},
      {"cityId": "191","cityName": "纽卡斯尔",},
      {"cityId": "312","cityName": "纽伦堡",},
      {"cityId": "742","cityName": "纽瓦克",},
      {"cityId": "43","cityName": "纽约",},
      {"cityId": "4557","cityName": "女皇镇（塔斯马尼亚）",},
      {"cityId": "1068","cityName": "诺丁汉",},
      {"cityId": "1311","cityName": "诺夫哥罗德",},
    ],
  },
  {
    name: 'O',
    city:[
      {"cityId": "127","cityName": "欧登塞"},
    ],
  },
  {
    name: 'P',
    city:[
      {"cityId": "953","cityName": "帕尔马(马略卡岛)",},
      {"cityId": "3533","cityName": "帕绍",},
      {"cityId": "4655","cityName": "派恩溪",},
      {"cityId": "179","cityName": "佩奇",},
      {"cityId": "8528","cityName": "平昌(滑雪场)",},
      {"cityId": "1036","cityName": "屏东",},
      {"cityId": "8524","cityName": "坡州",},
      {"cityId": "11","cityName": "珀斯",},
      {"cityId": "3967","cityName": "蒲种",},
      {"cityId": "4171","cityName": "浦安市",},
      {"cityId": "3865","cityName": "浦项市",},
      {"cityId": "235","cityName": "普吉岛",},
      {"cityId": "141","cityName": "普罗旺斯艾克斯",},
    ],
  },
  {
    name: 'Q',
    city:[
      {"cityId": "4126","cityName": "岐阜市",},
      {"cityId": "1011","cityName": "岐阜县",},
      {"cityId": "4096","cityName": "埼玉市",},
      {"cityId": "4131","cityName": "千岁",},
      {"cityId": "219","cityName": "千叶",},
      {"cityId": "4107","cityName": "千叶市",},
      {"cityId": "4136","cityName": "强罗",},
      {"cityId": "5131","cityName": "芹苴",},
      {"cityId": "4128","cityName": "轻井泽",},
      {"cityId": "5132","cityName": "清化",},
      {"cityId": "992","cityName": "清莱",},
      {"cityId": "232","cityName": "清迈",},
      {"cityId": "3442","cityName": "清州市",},
      {"cityId": "207","cityName": "庆州",},
      {"cityId": "3435","cityName": "全州",},
      {"cityId": "4267","cityName": "犬岛",},
      {"cityId": "4100","cityName": "群马县",},
    ],
  },
  {
    name: 'R',
    city:[
      {"cityId": "4083","cityName": "热海",},
      {"cityId": "3432","cityName": "仁川",},
      {"cityId": "4081","cityName": "日光市",},
      {"cityId": "162","cityName": "日内瓦",},
      {"cityId": "5134","cityName": "荣市",},
    ],
  },
  {
    name: 'S',
    city:[
      {"cityId": "1111","cityName": "萨尔堡",},
      {"cityId": "1797","cityName": "萨尔布吕肯",},
      {"cityId": "1245","cityName": "萨尔茨堡",},
      {"cityId": "1533","cityName": "萨格勒布",},
      {"cityId": "1106","cityName": "萨拉戈萨",},
      {"cityId": "8412","cityName": "塞班岛",},
      {"cityId": "3411","cityName": "塞班岛",},
      {"cityId": "169","cityName": "塞戈维亚",},
      {"cityId": "3680","cityName": "塞哥维亚",},
      {"cityId": "287","cityName": "塞维利亚",},
      {"cityId": "3863","cityName": "三陟",},
      {"cityId": "1016","cityName": "三重",},
      {"cityId": "556","cityName": "沙巴--亚庇",},
      {"cityId": "583","cityName": "沙迦",},
      {"cityId": "3467","cityName": "沙美岛",},
      {"cityId": "1008","cityName": "山梨县",},
      {"cityId": "4135","cityName": "山中湖",},
      {"cityId": "226","cityName": "神户",},
      {"cityId": "3738","cityName": "圣安德鲁斯",},
      {"cityId": "607","cityName": "圣巴巴拉",},
      {"cityId": "112","cityName": "圣保罗",},
      {"cityId": "134","cityName": "圣彼得堡",},
      {"cityId": "5510","cityName": "圣彼得镇",},
      {"cityId": "262","cityName": "圣地亚哥",},
      {"cityId": "955","cityName": "圣港",},
      {"cityId": "5425","cityName": "圣戈阿尔",},
      {"cityId": "1250","cityName": "圣吉尔根",},
      {"cityId": "4710","cityName": "施里斯海姆",},
      {"cityId": "3556","cityName": "施派尔",},
      {"cityId": "5419","cityName": "施特拉尔松德",},
      {"cityId": "3547","cityName": "施万高",},
      {"cityId": "979","cityName": "什切青",},
      {"cityId": "3539","cityName": "什未林",},
      {"cityId": "3955","cityName": "士姑来",},
      {"cityId": "204","cityName": "首尔",},
      {"cityId": "3437","cityName": "束草",},
      {"cityId": "3427","cityName": "水原市",},
      {"cityId": "8529","cityName": "顺天",},
      {"cityId": "159","cityName": "斯德哥尔摩",},
      {"cityId": "3781","cityName": "斯蒂芬斯港",},
      {"cityId": "5380","cityName": "斯卡恩",},
      {"cityId": "1411","cityName": "斯里巴加湾市",},
      {"cityId": "1232","cityName": "斯塔万格",},
      {"cityId": "870","cityName": "斯特拉斯堡",},
      {"cityId": "3739","cityName": "斯特灵",},
      {"cityId": "1090","cityName": "斯图加特",},
      {"cityId": "1065","cityName": "斯旺西",},
      {"cityId": "4597","cityName": "斯旺希尔",},
      {"cityId": "4163","cityName": "松岛",},
      {"cityId": "6111","cityName": "松恩峡湾",},
      {"cityId": "163","cityName": "苏黎世",},
      {"cityId": "234","cityName": "苏梅岛",},
      {"cityId": "202","cityName": "宿务",},
      {"cityId": "1265","cityName": "索波特",},
      {"cityId": "135","cityName": "索契",},
      {"cityId": "12","cityName": "塔斯马尼亚",},
    ],
  },
  {
    name: 'T',
    city:[
      {"cityId": "276","cityName": "台北",},
      {"cityId": "1038","cityName": "台东",},
      {"cityId": "278","cityName": "台南",},
      {"cityId": "279","cityName": "台中",},
      {"cityId": "147","cityName": "坦佩雷",},
      {"cityId": "1041","cityName": "桃园",},
      {"cityId": "17","cityName": "陶波",},
      {"cityId": "1405","cityName": "特拉维夫",},
      {"cityId": "5418","cityName": "特里贝格",},
      {"cityId": "3512","cityName": "特里尔",},
      {"cityId": "1369","cityName": "特隆赫姆",},
      {"cityId": "4702","cityName": "特罗斯多夫",},
      {"cityId": "3444","cityName": "天安市",},
      {"cityId": "6573","cityName": "天空之岛",},
      {"cityId": "5128","cityName": "头顿",},
      {"cityId": "3528","cityName": "图宾根",},
      {"cityId": "3630","cityName": "图恩",},
      {"cityId": "1070","cityName": "图尔",},
      {"cityId": "148","cityName": "图尔库",},
      {"cityId": "301","cityName": "图卢兹",},
      {"cityId": "866","cityName": "土伦",},
      {"cityId": "1103","cityName": "托莱多",},
      {"cityId": "781","cityName": "托莱多(俄亥俄州)",},
    ],
  },
  {
    name: 'W',
    city:[
      {"cityId": "3681","cityName": "瓦伦西亚",},
      {"cityId": "4676","cityName": "瓦纳卡",},
      {"cityId": "34","cityName": "瓦纳卡湖",},
      {"cityId": "1278","cityName": "万象",},
      {"cityId": "4087","cityName": "网走",},
      {"cityId": "3740","cityName": "威廉堡",},
      {"cityId": "182","cityName": "威尼斯",},
      {"cityId": "3522","cityName": "威斯巴登",},
      {"cityId": "258","cityName": "维多利亚",},
      {"cityId": "3505","cityName": "维尔茨堡",},
      {"cityId": "1098","cityName": "维罗纳",},
      {"cityId": "117","cityName": "维也纳",},
      {"cityId": "502","cityName": "蔚山",},
      {"cityId": "5487","cityName": "魏恩海姆",},
      {"cityId": "3517","cityName": "魏玛",},
      {"cityId": "36","cityName": "温哥华",},
      {"cityId": "1323","cityName": "温切斯特",},
      {"cityId": "1397","cityName": "温莎",},
      {"cityId": "271","cityName": "温莎",},
      {"cityId": "3523","cityName": "沃尔夫斯堡",},
      {"cityId": "5446","cityName": "沃尔姆斯",},
      {"cityId": "1233","cityName": "沃斯",},
      {"cityId": "677","cityName": "沃特敦(纽约州)",},
      {"cityId": "41","cityName": "渥太华",},
      {"cityId": "4995","cityName": "乌布",},
      {"cityId": "3516","cityName": "乌尔姆",},
      {"cityId": "212","cityName": "乌兰巴托",},
      {"cityId": "1048","cityName": "乌姆盖万",},
      {"cityId": "1345","cityName": "乌普萨拉",},
      {"cityId": "1144","cityName": "伍伦贡",},
      {"cityId": "3537","cityName": "伍珀塔尔",},
      {"cityId": "4181","cityName": "武藏野市",},
    ],
  },
  {
    name: 'X',
    city:[
      {"cityId": "3859","cityName": "西归浦",},
      {"cityId": "3868","cityName": "西哈努克市",},
      {"cityId": "48","cityName": "西雅图",},
      {"cityId": "679","cityName": "西棕榈滩",},
      {"cityId": "4698","cityName": "希尔德斯海姆",},
      {"cityId": "5379","cityName": "希勒勒",},
      {"cityId": "4713","cityName": "希特多夫",},
      {"cityId": "1","cityName": "悉尼",},
      {"cityId": "3557","cityName": "锡根",},
      {"cityId": "5121","cityName": "下龙市",},
      {"cityId": "5120","cityName": "下龙湾",},
      {"cityId": "1013","cityName": "下吕",},
      {"cityId": "4151","cityName": "下吕市",},
      {"cityId": "68","cityName": "夏洛特",},
      {"cityId": "285","cityName": "夏威夷大岛",},
      {"cityId": "284","cityName": "夏威夷茂宜岛",},
      {"cityId": "46","cityName": "夏威夷欧胡岛（檀香山）",},
      {"cityId": "544","cityName": "仙台",},
      {"cityId": "290","cityName": "暹粒",},
      {"cityId": "1292","cityName": "岘港",},
      {"cityId": "4208","cityName": "相模原市",},
      {"cityId": "1269","cityName": "香港",},
      {"cityId": "3351","cityName": "箱根",},
      {"cityId": "1288","cityName": "象岛",},
      {"cityId": "1313","cityName": "谢尔盖耶夫",},
      {"cityId": "839","cityName": "谢菲尔德",},
      {"cityId": "5412","cityName": "辛根",},
      {"cityId": "1107","cityName": "辛特拉",},
      {"cityId": "1042","cityName": "新北",},
      {"cityId": "561","cityName": "新德里",},
      {"cityId": "239","cityName": "新加坡",},
      {"cityId": "1275","cityName": "新山",},
      {"cityId": "4095","cityName": "新潟市",},
      {"cityId": "560","cityName": "新仙（柔佛巴鲁）",},
      {"cityId": "549","cityName": "新泻",},
      {"cityId": "1040","cityName": "新竹",},
      {"cityId": "8589","cityName": "星野度假村",},
      {"cityId": "3455","cityName": "熊本市",},
      {"cityId": "58","cityName": "休斯敦",},
      {"cityId": "3936","cityName": "雪邦",},
    ],
  },
  {
    name: 'Y',
    city:[
      {"cityId": "3861","cityName": "牙山",},
      {"cityId": "1435","cityName": "芽庄",},
      {"cityId": "173","cityName": "雅典",},
      {"cityId": "247","cityName": "雅加达",},
      {"cityId": "3507","cityName": "亚琛",},
      {"cityId": "59","cityName": "亚特兰大",},
      {"cityId": "1349","cityName": "延雪平",},
      {"cityId": "628","cityName": "盐湖城",},
      {"cityId": "3601","cityName": "羊角村",},
      {"cityId": "1126","cityName": "阳光海岸",},
      {"cityId": "8526","cityName": "杨平",},
      {"cityId": "1283","cityName": "仰光",},
      {"cityId": "3536","cityName": "耶拿",},
      {"cityId": "4618","cityName": "伊登",},
      {"cityId": "4080","cityName": "伊豆半岛",},
      {"cityId": "3343","cityName": "伊豆市",},
      {"cityId": "1417","cityName": "伊尔库茨克",},
      {"cityId": "165","cityName": "伊斯坦布尔",},
      {"cityId": "1343","cityName": "伊瓦洛",},
      {"cityId": "534","cityName": "伊滋密尔",},
      {"cityId": "1043","cityName": "宜兰",},
      {"cityId": "559","cityName": "怡保",},
      {"cityId": "6574","cityName": "因弗尼斯",},
      {"cityId": "3521","cityName": "因戈尔施塔特",},
      {"cityId": "1121","cityName": "因尼斯费尔",},
      {"cityId": "120","cityName": "因斯布鲁克",},
      {"cityId": "1209","cityName": "因特拉肯",},
      {"cityId": "1084","cityName": "英戈尔施塔特",},
      {"cityId": "5136","cityName": "永隆",},
      {"cityId": "3599","cityName": "于韦斯屈莱",},
      {"cityId": "554","cityName": "宇都宫",},
      {"cityId": "3456","cityName": "宇治市",},
      {"cityId": "3864","cityName": "郁陵岛",},
      {"cityId": "4102","cityName": "御殿场市",},
      {"cityId": "78","cityName": "约翰内斯堡",},
      {"cityId": "1315","cityName": "约克",},
    ],
  },{
    name: 'Z',
    city:[
      {"cityId": "1031","cityName": "云顶高原",},
      {"cityId": "4534","cityName": "泽西城",},
      {"cityId": "3441","cityName": "正东津",},
      {"cityId": "4099","cityName": "支笏湖",},
      {"cityId": "47","cityName": "芝加哥",},
      {"cityId": "3860","cityName": "忠州",},
      {"cityId": "5139","cityName": "朱笃",},
      {"cityId": "3463","cityName": "佐贺市",}
    ],
  },
];
